# permissions for end users to view singledeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: singledeployment-viewer-role
rules:
- apiGroups:
  - deployment.github.com
  resources:
  - singledeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deployment.github.com
  resources:
  - singledeployments/status
  verbs:
  - get
