apiVersion: deployment.github.com/v1
kind: SingleDeployment
metadata:
  name: singledeployment-sample
spec:
  # TODO(user): Add fields here
  port: 80
  image: nginx:latest
  replicas: 2
  expose:
    mode: ingress
    ingressDomain: cloud.madongming.com
